/** Shared English copy for the Loans module. */
export const loanCopy = {
  pageTitle: 'Loans',
  pageSubtitle: 'Track bank loans, rates, and link ledger transactions',
  addLoan: 'Add loan',
  addFirstLoan: 'Add first loan',
  totalOutstanding: 'Total outstanding',
  activeLoans: (n: number) => `${n} active`,
  totalMonthly: 'Total monthly payment',
  weightedAvgRate: 'Weighted avg. rate',
  noLoans: 'No loans yet',
  noLoansHint: 'Add a bank loan with rate, remaining principal, monthly payment, and disbursement card.',
  loadFailed: 'Failed to load',
  deleted: 'Deleted',
  deleteFailed: 'Delete failed',
  editDetails: 'Edit details',
  linkTransactions: 'Link transactions',
  delete: 'Delete',
  deleteConfirm: (name: string) => `Delete loan for ${name}? Linked transactions will be unlinked.`,
  totalPrincipal: 'Total',
  remaining: 'Remaining',
  principalProgress: 'Principal progress',
  linkedRepayments: 'Linked repayments',
  linkedRepaymentHint: (n: number) => `${n} txns · incl. interest`,
  installments: 'Installments',
  installmentHint: '> ¥100 counts as 1',
  monthly: 'Monthly',
  maturity: 'Maturity',
  closed: 'Closed',
  disbursementCard: 'Disbursement card',
  link: 'Link',
  edit: 'Edit',
  actions: 'Actions',
} as const

export const LOAN_DATE_PRESETS = [
  { label: '3 months', value: '3m' as const },
  { label: '6 months', value: '6m' as const },
  { label: '1 year', value: '1y' as const },
  { label: 'All', value: 'all' as const },
]

export const loanLinkCopy = {
  infoBar: (min: number) =>
    `Link transactions to trace disbursements/repayments. Repaid amount and installment count are auto-calculated from REPAYMENT links (each > ¥${min} counts as one installment). Remaining principal is not changed.`,
  filterChip: (label: string, cardRole: string) => `Filter: ${label} · ${cardRole} card transactions`,
  disbursementCardRole: 'Disbursement',
  repaymentCardRole: 'Repayment',
  linkedCount: 'Linked',
  linkedSub: 'transactions',
  qualifyingPeriods: 'Qualifying installments',
  smallSkipped: (n: number) => `${n} small txns excluded`,
  perInstallmentRule: '> ¥100 each',
  repaymentTotal: 'Repayment total',
  allTotal: (amt: string) => `All ${amt}`,
  disbursement: 'Disbursement',
  interest: 'Interest',
  linkedSection: 'Linked transactions',
  pickSection: 'Pick transaction to link',
  candidates: (n: number) => `${n} available`,
  setCardWarning: 'Set a disbursement card under Details before filtering transactions.',
  searchPlaceholder: 'Search description, card…',
  loadingTxns: 'Loading transactions…',
  noLinked: 'No links yet',
  noCandidates: (label: string) => `No linkable transactions for "${label}" in this period`,
  noCardSet: 'Disbursement card not set',
  linked: 'Linked',
  unlink: 'Unlink',
  unlinkConfirm: 'Remove link?',
  link: 'Link',
  linkedOk: 'Linked',
  unlinkedOk: 'Unlinked',
  linkFailed: 'Link failed',
  unlinkFailed: 'Unlink failed',
  countsAsInstallment: 'Counts as 1',
  skipInstallment: 'Skip count',
  skipInstallmentTip: (min: number) => `Amount ≤ ¥${min} — not counted toward installments`,
  txnCount: (n: number) => `${n} txns`,
} as const

export const loanFormCopy = {
  saved: 'Saved',
  created: 'Loan added',
  lender: 'Lender bank',
  lenderRequired: 'Enter bank name',
  lenderPlaceholder: 'e.g. Bank of Communications',
  alias: 'Alias (optional)',
  aliasPlaceholder: 'e.g. Business loan A',
  principal: 'Principal (¥)',
  remaining: 'Remaining (¥)',
  remainingNegative: 'Cannot be negative',
  remainingExceeds: 'Cannot exceed principal',
  apr: 'APR (%)',
  monthly: 'Monthly payment (¥)',
  termMonths: 'Term (months)',
  termExtra: 'Total term; paid installments are auto-calculated from linked repayments',
  termPlaceholder: 'e.g. 60',
  maturity: 'Maturity date',
  disbursementCard: 'Disbursement card',
  disbursementRequired: 'Select disbursement card',
  disbursementExtra: 'Card that received loan proceeds',
  noCards: 'No bank cards yet',
  noCardsHint: 'Add a bank card to select disbursement account and link transactions.',
  addCard: 'Add bank card',
  selectCard: 'Select card',
  addNewCard: 'Add new card',
  manageCards: 'Manage cards',
  repaymentCard: 'Repayment card (optional)',
  repaymentExtra: 'Fill in when different from disbursement card',
  sameAsDisbursement: 'Same as disbursement',
  repaymentMethod: 'Repayment method',
  status: 'Status',
  active: 'Active',
  closed: 'Closed',
  notes: 'Notes',
  notesPlaceholder: 'Maturity notes, card verification, etc.',
  saveCreate: 'Add loan',
  saveEdit: 'Save changes',
  tabDetail: 'Details',
  tabLinks: 'Links',
  createTitle: 'Add loan',
  editTitle: 'Edit loan',
} as const
