package com.finsight.domain.model;

/** Semantic monthly metrics stored in fin_metric_monthly. */
public enum MetricCode {
    INCOME_TOTAL,
    EXPENSE_TOTAL,
    NET_CASHFLOW,
    SAVINGS_RATE,
    FIXED_EXPENSE_RATIO,
    UNCLASSIFIED_COUNT,
    TRANSFER_TOTAL,
    TRANSACTION_COUNT,
    REAL_INCOME,
    REFUND_INFLOW,
    REIMBURSEMENT_INFLOW,
    CONSUMPTION_EXPENSE,
    FIXED_EXPENSE,
    VARIABLE_EXPENSE,
    DISCRETIONARY_EXPENSE,
    ESSENTIAL_EXPENSE,
    INVESTMENT_INFLOW,
    INVESTMENT_OUTFLOW,
    LIABILITY_INFLOW,
    LIABILITY_REPAYMENT,
    TRANSFER_IN,
    TRANSFER_OUT,
    FEE_EXPENSE,
    UNCLASSIFIED_AMOUNT,
    OTHER_AMOUNT,
    DATA_QUALITY_SCORE
}
