-- Minimal bootstrap for empty databases (Testcontainers / fresh installs).
CREATE TABLE IF NOT EXISTS transaction (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    version INT NOT NULL DEFAULT 0,
    created_by VARCHAR(255) NULL,
    created_at DATETIME(6) NULL,
    updated_by VARCHAR(255) NULL,
    updated_at DATETIME(6) NULL,
    card_id VARCHAR(64) NULL,
    bank_card_id VARCHAR(64) NULL,
    bank_card_name VARCHAR(128) NULL,
    transaction_date DATETIME(6) NULL,
    bookkeeping_date DATETIME(6) NULL,
    transaction_desc TEXT NULL,
    balance_currency VARCHAR(20) NULL,
    balance_money DECIMAL(19,4) NULL,
    income_money DECIMAL(19,4) NULL,
    card_type_id INT NULL,
    card_type_name VARCHAR(255) NULL,
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    consumption_type INT NULL,
    consume_id VARCHAR(64) NULL,
    consume_code VARCHAR(64) NULL,
    consume_name VARCHAR(255) NULL,
    memo TEXT NULL,
    statement_id VARCHAR(64) NULL,
    opponent_account VARCHAR(64) NULL,
    opponent_name VARCHAR(128) NULL,
    transaction_time VARCHAR(32) NULL,
    account_balance DECIMAL(19,4) NULL,
    txn_kind VARCHAR(16) NULL,
    transfer_group_id VARCHAR(64) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
