/** Shared English copy for Admin pages. */
export const adminCardsCopy = {
  title: 'Bank cards',
  subtitle: 'Manage account cards for statement import and loan transaction linking',
  addCard: 'Add card',
  addFirstCard: 'Add first card',
  deleted: 'Deleted',
  deleteFailed: 'Delete failed',
  edit: 'Edit',
  delete: 'Delete',
  deleteConfirm: 'Delete this bank card?',
  loadFailed: 'Failed to load',
  actions: 'Actions',
  totalCards: 'Total cards',
  debitCards: 'Debit',
  creditCards: 'Credit',
  noCards: 'No bank cards yet',
  noCardsHint: 'Add a card to import statements and link loan disbursement/repayment transactions.',
  drawerEditTitle: 'Edit bank card',
  drawerAddTitle: 'Add bank card',
  drawerSave: 'Save',
  drawerAdd: 'Add',
  cardUpdated: 'Bank card updated',
  cardAdded: 'Bank card added',
  selectBank: 'Select bank',
  drawerHint: 'Used for statement import and loan transaction linking',
  bankLabel: 'Bank',
  bankRequired: 'Select a bank',
  cardTypeLabel: 'Card type',
  cardNoLabel: 'Card / account number',
  cardNoRequired: 'Enter card or account number',
  cardNoExtra: 'Full number or last 4 digits — used to match transactions',
  cardNoPlaceholder: 'e.g. 6222… or 1234',
  displayNameLabel: 'Display name (optional)',
  displayNamePlaceholder: 'e.g. CCB salary card',
} as const
