-- FinSight L2 category Sprint 2 seed (Issue #69).
-- MANUAL ONLY — review before execution. Does NOT batch-update historical transactions.
--
--   mysql -u <user> -p finsight < docs/tech/database/l2-category-sprint2-seed.sql
--
-- Prerequisites: Flyway V23 (report_role column). Verify L1 parents exist or use Step 0 below.
-- After apply: add rules in Rule Engine; do not bulk-recategorize txns without migration batch (#75).

-- Generated from ClassificationL2TargetCatalog — Issue #69
-- Manual execution only; never auto-applied by Flyway.

-- Step 0: ensure L1 roots exist (insert if missing)
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'INCOME', 'INCOME', '收入', 1, null, 10, 'income', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'INCOME');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'FIXED', 'FIXED', '固定支出', 1, null, 20, 'expense', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FIXED');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'LIVING', 'LIVING', '日常生活', 1, null, 30, 'expense', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'LIVING');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'SHOPPING', 'SHOPPING', '购物与耐用品', 1, null, 40, 'expense', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'SHOPPING');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'TRAVEL', 'TRAVEL', '交通与车辆', 1, null, 50, 'expense', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'TRAVEL');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'EDU', 'EDU', '教育与培训', 1, null, 55, 'expense', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'EDU');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'ENT', 'ENT', '娱乐与旅行', 1, null, 60, 'expense', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ENT');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'GIFT', 'GIFT', '人情与公益', 1, null, 65, 'expense', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'GIFT');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'REIM', 'REIM', '报销与返还', 1, null, 70, 'income,refund', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'REIM');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'ASSET', 'ASSET', '资产变动', 1, null, 75, 'transfer,asset', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ASSET');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'LIABILITY', 'LIABILITY', '负债变动', 1, null, 80, 'transfer,liability', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'LIABILITY');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'INVEST', 'INVEST', '投资活动', 1, null, 85, 'expense,invest', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'INVEST');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'WEALTH', 'WEALTH', '理财与金融产品', 1, null, 90, 'invest', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'WEALTH');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'FEE', 'FEE', '金融手续费', 1, null, 92, 'expense', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FEE');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, deleted, version, created_at, updated_at) select 'OTHER', 'OTHER', '其它消费', 1, null, 99, 'expense', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'OTHER');

insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ASSET-01', 'ASSET-01', 'ATM 取现', 2, 'ASSET', 1, 'transfer,asset', 'asset', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ASSET-01');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ASSET-02', 'ASSET-02', '账户间转入转出', 2, 'ASSET', 2, 'transfer', 'transfer', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ASSET-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ASSET-03', 'ASSET-03', '余额调整', 2, 'ASSET', 3, 'transfer,asset', 'asset', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ASSET-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ASSET-04', 'ASSET-04', '储蓄转入', 2, 'ASSET', 4, 'transfer,asset', 'asset', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ASSET-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ASSET-05', 'ASSET-05', '资产购买', 2, 'ASSET', 5, 'transfer,asset', 'asset', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ASSET-05');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'EDU-01', 'EDU-01', '学费培训', 2, 'EDU', 1, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'EDU-01');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'EDU-02', 'EDU-02', '书籍资料', 2, 'EDU', 2, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'EDU-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ENT-01', 'ENT-01', '酒店住宿', 2, 'ENT', 1, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ENT-01');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ENT-02', 'ENT-02', '景点门票', 2, 'ENT', 2, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ENT-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ENT-03', 'ENT-03', '电影演出', 2, 'ENT', 3, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ENT-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ENT-04', 'ENT-04', '游戏娱乐', 2, 'ENT', 4, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ENT-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ENT-05', 'ENT-05', '旅游消费', 2, 'ENT', 5, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ENT-05');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'ENT-06', 'ENT-06', '运动健身', 2, 'ENT', 6, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'ENT-06');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FEE-01', 'FEE-01', '银行手续费', 2, 'FEE', 1, 'expense', 'cashflow', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FEE-01');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FEE-02', 'FEE-02', '信用卡年费', 2, 'FEE', 2, 'expense', 'cashflow', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FEE-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FEE-03', 'FEE-03', '证券手续费', 2, 'FEE', 3, 'expense', 'cashflow', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FEE-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FEE-04', 'FEE-04', '分期手续费', 2, 'FEE', 4, 'expense', 'cashflow', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FEE-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FEE-05', 'FEE-05', '汇兑手续费', 2, 'FEE', 5, 'expense', 'cashflow', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FEE-05');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FIXED-01', 'FIXED-01', '房租/房贷', 2, 'FIXED', 1, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FIXED-01');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FIXED-02', 'FIXED-02', '物业/水电燃气', 2, 'FIXED', 2, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FIXED-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FIXED-03', 'FIXED-03', '通信网络', 2, 'FIXED', 3, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FIXED-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FIXED-04', 'FIXED-04', '保险', 2, 'FIXED', 4, 'expense', 'cashflow', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FIXED-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FIXED-05', 'FIXED-05', '会员订阅', 2, 'FIXED', 5, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FIXED-05');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FIXED-06', 'FIXED-06', '教育固定缴费', 2, 'FIXED', 6, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FIXED-06');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FIXED-07', 'FIXED-07', '固定还款', 2, 'FIXED', 7, 'expense', 'liability', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FIXED-07');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'FIXED-99', 'FIXED-99', '其他固定支出', 2, 'FIXED', 99, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'FIXED-99');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'GIFT-01', 'GIFT-01', '红包礼金', 2, 'GIFT', 1, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'GIFT-01');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'GIFT-02', 'GIFT-02', '转账赠与', 2, 'GIFT', 2, 'expense,transfer', 'transfer', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'GIFT-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'GIFT-03', 'GIFT-03', '公益捐赠', 2, 'GIFT', 3, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'GIFT-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'GIFT-04', 'GIFT-04', '家庭支持', 2, 'GIFT', 4, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'GIFT-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'INCOME-01', 'INCOME-01', '工资薪金', 2, 'INCOME', 1, 'income', 'income', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'INCOME-01');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'INCOME-02', 'INCOME-02', '副业经营', 2, 'INCOME', 2, 'income', 'income', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'INCOME-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'INCOME-03', 'INCOME-03', '投资收益', 2, 'INCOME', 3, 'income,invest', 'investment', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'INCOME-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'INCOME-99', 'INCOME-99', '其他收入', 2, 'INCOME', 99, 'income', 'income', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'INCOME-99');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'INVEST-03', 'INVEST-03', '股票买入', 2, 'INVEST', 3, 'expense,invest', 'investment', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'INVEST-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'INVEST-04', 'INVEST-04', '股票卖出', 2, 'INVEST', 4, 'income,invest', 'investment', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'INVEST-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'INVEST-05', 'INVEST-05', '证券转账', 2, 'INVEST', 5, 'transfer,invest', 'investment', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'INVEST-05');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'INVEST-06', 'INVEST-06', '基金赎回', 2, 'INVEST', 6, 'income,invest', 'investment', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'INVEST-06');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DEBT-01', 'DEBT-01', '信用卡还款', 2, 'LIABILITY', 1, 'transfer,liability', 'liability', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DEBT-01');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DEBT-02', 'DEBT-02', '借款收到', 2, 'LIABILITY', 2, 'transfer,liability', 'liability', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DEBT-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DEBT-03', 'DEBT-03', '贷款还款', 2, 'LIABILITY', 3, 'expense,liability', 'liability', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DEBT-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DEBT-04', 'DEBT-04', '分期还款', 2, 'LIABILITY', 4, 'expense,liability', 'liability', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DEBT-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DEBT-05', 'DEBT-05', '利息支出', 2, 'LIABILITY', 5, 'expense', 'cashflow', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DEBT-05');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DAILY-02', 'DAILY-02', '外卖', 2, 'LIVING', 2, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DAILY-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DAILY-03', 'DAILY-03', '超市便利', 2, 'LIVING', 3, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DAILY-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DAILY-04', 'DAILY-04', '日用品', 2, 'LIVING', 4, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DAILY-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DAILY-05', 'DAILY-05', '医疗药品', 2, 'LIVING', 5, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DAILY-05');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DAILY-06', 'DAILY-06', '宠物', 2, 'LIVING', 6, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DAILY-06');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'DAILY-07', 'DAILY-07', '家政维修', 2, 'LIVING', 7, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'DAILY-07');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'OTHER-02', 'OTHER-02', '低频小额未知商户', 2, 'OTHER', 2, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'OTHER-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'OTHER-03', 'OTHER-03', '待人工确认', 2, 'OTHER', 3, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'OTHER-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'REIM-01', 'REIM-01', '公司报销', 2, 'REIM', 1, 'income,refund', 'refund', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'REIM-01');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'REIM-02', 'REIM-02', '消费退款', 2, 'REIM', 2, 'income,refund', 'refund', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'REIM-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'REIM-03', 'REIM-03', '押金返还', 2, 'REIM', 3, 'income,refund', 'refund', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'REIM-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'REIM-04', 'REIM-04', '平台返现', 2, 'REIM', 4, 'income,refund', 'refund', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'REIM-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'REIM-05', 'REIM-05', '信用卡退货', 2, 'REIM', 5, 'income,refund', 'refund', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'REIM-05');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'SHOP-02', 'SHOP-02', '数码家电', 2, 'SHOPPING', 2, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'SHOP-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'SHOP-03', 'SHOP-03', '家居家装', 2, 'SHOPPING', 3, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'SHOP-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'SHOP-04', 'SHOP-04', '母婴儿童', 2, 'SHOPPING', 4, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'SHOP-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'SHOP-05', 'SHOP-05', '大件耐用品', 2, 'SHOPPING', 5, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'SHOP-05');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'SHOP-06', 'SHOP-06', '电商购物', 2, 'SHOPPING', 6, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'SHOP-06');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'TRANS-02', 'TRANS-02', '打车/网约车', 2, 'TRAVEL', 2, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'TRANS-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'TRANS-03', 'TRANS-03', '油费/充电', 2, 'TRAVEL', 3, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'TRANS-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'TRANS-04', 'TRANS-04', '停车', 2, 'TRAVEL', 4, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'TRANS-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'TRANS-05', 'TRANS-05', '保养维修', 2, 'TRAVEL', 5, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'TRANS-05');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'TRANS-06', 'TRANS-06', '车辆保险', 2, 'TRAVEL', 6, 'expense', 'cashflow', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'TRANS-06');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'TRANS-07', 'TRANS-07', '机票/火车', 2, 'TRAVEL', 7, 'expense', 'budget', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'TRANS-07');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'WEALTH-01', 'WEALTH-01', '银行理财申购', 2, 'WEALTH', 1, 'expense,invest', 'investment', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'WEALTH-01');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'WEALTH-02', 'WEALTH-02', '银行理财赎回', 2, 'WEALTH', 2, 'income,invest', 'investment', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'WEALTH-02');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'WEALTH-03', 'WEALTH-03', '货币基金', 2, 'WEALTH', 3, 'invest', 'investment', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'WEALTH-03');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'WEALTH-04', 'WEALTH-04', '定期存款', 2, 'WEALTH', 4, 'transfer,invest', 'investment', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'WEALTH-04');
insert into cls_category (id, code, name, level, parent_id, sort_no, txn_types, report_role, deleted, version, created_at, updated_at) select 'WEALTH-05', 'WEALTH-05', '结构性产品', 2, 'WEALTH', 5, 'invest', 'investment', 0, 0, now(), now() from dual where not exists (select 1 from cls_category where code = 'WEALTH-05');

-- Optional name clarifications (does NOT change code)

update cls_category set name = '临时无法归类', updated_at = now() where code = 'OTHER-01' and coalesce(deleted, 0) = 0 and name = '无法归类的支出';
update cls_category set name = '投资未分类', updated_at = now() where code = 'INVEST-OTHER' and coalesce(deleted, 0) = 0 and name = '其它消费';
update cls_category set name = '其它消费', updated_at = now() where code = 'OTHER' and coalesce(deleted, 0) = 0 and name = '其他类别' and level = 1;

-- Backfill report_role for catalog codes (requires V23 column)

update cls_category set report_role = 'income' where code = 'INCOME-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'income' where code = 'INCOME-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'INCOME-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'income' where code = 'INCOME-99' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'FIXED-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'FIXED-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'FIXED-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'cashflow' where code = 'FIXED-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'FIXED-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'FIXED-06' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'liability' where code = 'FIXED-07' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'FIXED-99' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'DAILY-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'DAILY-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'DAILY-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'DAILY-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'DAILY-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'DAILY-06' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'DAILY-07' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'SHOP-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'SHOP-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'SHOP-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'SHOP-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'SHOP-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'SHOP-06' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'TRAVEL-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'TRANS-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'TRANS-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'TRANS-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'TRANS-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'cashflow' where code = 'TRANS-06' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'TRANS-07' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'ENT-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'ENT-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'ENT-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'ENT-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'ENT-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'ENT-06' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'EDU-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'EDU-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'GIFT-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'transfer' where code = 'GIFT-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'GIFT-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'GIFT-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'refund' where code = 'REIM-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'refund' where code = 'REIM-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'refund' where code = 'REIM-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'refund' where code = 'REIM-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'refund' where code = 'REIM-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'asset' where code = 'ASSET-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'transfer' where code = 'ASSET-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'asset' where code = 'ASSET-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'asset' where code = 'ASSET-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'asset' where code = 'ASSET-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'liability' where code = 'DEBT-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'liability' where code = 'DEBT-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'liability' where code = 'DEBT-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'liability' where code = 'DEBT-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'cashflow' where code = 'DEBT-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'INVEST-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'INVEST-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'INVEST-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'INVEST-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'INVEST-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'INVEST-06' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'WEALTH-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'WEALTH-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'WEALTH-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'WEALTH-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'investment' where code = 'WEALTH-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'cashflow' where code = 'FEE-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'cashflow' where code = 'FEE-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'cashflow' where code = 'FEE-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'cashflow' where code = 'FEE-04' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'cashflow' where code = 'FEE-05' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'OTHER-01' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'OTHER-02' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
update cls_category set report_role = 'budget' where code = 'OTHER-03' and coalesce(deleted, 0) = 0 and (report_role is null or trim(report_role) = '');
